@echo off
set OS_PRIVATE_KEY_PATH=C:\\Users\\Admin\\Downloads\\raulchoque.pem
set OS_AUTH_URL=http://10.28.3.240:5000/v3
set OS_IDENTITY_API_VERSION=3
set OS_TENANT_NAME=2099bc1dc3ec4c76a9cdbab47ea675a7
set OS_PROJECT_NAME=fj_at09
set OS_USERNAME=raulchoque
set OS_PASSWORD=put.your.password
set OS_DOMAIN_NAME=fundacion-jala
set OS_FLAVOR=student.2.2R
set OS_IMAGE=ubuntu-16.04-amd64-server_20190215
set OS_KEY_PAIR_NAME=raulchoque
set OS_INITIAL_NAME=RACH
set OS_REGION_NAME=bootstack-jalasoft
